In [2]:
!python -m pip install -U python-woc pandas matplotlib
# please clear the output of this cell in your notebook before checking it in

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: python-woc in /home/smurph61/.local/lib/python3.9/site-packages (0.4.1)
Requirement already satisfied: pandas in /home/smurph61/.local/lib/python3.9/site-packages (2.3.3)
Requirement already satisfied: matplotlib in /home/smurph61/.local/lib/python3.9/site-packages (3.9.4)
Requirement already satisfied: chardet<6.0.0,>=5.2.0 in /home/smurph61/.local/lib/python3.9/site-packages (from python-woc) (5.2.0)
Requirement already satisfied: tqdm<5.0.0,>=4.65.0 in /home/smurph61/.local/lib/python3.9/site-packages (from python-woc) (4.70.0)
Requirement already satisfied: python-lzf<0.3.0,>=0.2.4 in /home/smurph61/.local/lib/python3.9/site-packages (from python-woc) (0.2.6)
Requirement already satisfied: rapidgzip<0.15.0,>=0.14.3 in /home/smurph61/.local/lib/python3.9/site-packages (from python-woc) (0.14.5)
Requirement already satisfied: httpx<0.29.0,>=0.28.1 in /home/smurph61/.local/lib/python3.9/site-packages (from python-woc) (0.28.1)
Requirement already satisfied: numpy>=1.22.4 in /usr/lib64/python3.9/site-packages (from pandas) (1.23.5)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3.9/site-packages (from pandas) (2021.1)
Requirement already satisfied: tzdata>=2022.7 in /home/smurph61/.local/lib/python3.9/site-packages (from pandas) (2026.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/lib/python3.9/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: fonttools>=4.22.0 in /home/smurph61/.local/lib/python3.9/site-packages (from matplotlib) (4.60.2)
Requirement already satisfied: importlib-resources>=3.2.0 in /home/smurph61/.local/lib/python3.9/site-packages (from matplotlib) (6.5.2)
Requirement already satisfied: packaging>=20.0 in /home/smurph61/.local/lib/python3.9/site-packages (from matplotlib) (26.3)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/lib/python3.9/site-packages (from matplotlib) (2.4.7)
Requirement already satisfied: cycler>=0.10 in /usr/lib/python3.9/site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: contourpy>=1.0.1 in /home/smurph61/.local/lib/python3.9/site-packages (from matplotlib) (1.3.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/lib64/python3.9/site-packages (from matplotlib) (1.4.1)
Requirement already satisfied: pillow>=8 in /usr/lib64/python3.9/site-packages (from matplotlib) (10.0.1)
Requirement already satisfied: certifi in /home/smurph61/.local/lib/python3.9/site-packages (from httpx<0.29.0,>=0.28.1->python-woc) (2026.7.22)
Requirement already satisfied: anyio in /home/smurph61/.local/lib/python3.9/site-packages (from httpx<0.29.0,>=0.28.1->python-woc) (4.12.1)
Requirement already satisfied: httpcore==1.* in /home/smurph61/.local/lib/python3.9/site-packages (from httpx<0.29.0,>=0.28.1->python-woc) (1.0.9)
Requirement already satisfied: idna in /usr/lib/python3.9/site-packages (from httpx<0.29.0,>=0.28.1->python-woc) (2.10)
Requirement already satisfied: h11>=0.16 in /home/smurph61/.local/lib/python3.9/site-packages (from httpcore==1.*->httpx<0.29.0,>=0.28.1->python-woc) (0.16.0)
Requirement already satisfied: zipp>=3.1.0 in /usr/local/lib/python3.9/site-packages (from importlib-resources>=3.2.0->matplotlib) (3.23.0)
Requirement already satisfied: six>=1.5 in /usr/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.15.0)
Requirement already satisfied: typing_extensions>=4.5 in /usr/local/lib/python3.9/site-packages (from anyio->httpx<0.29.0,>=0.28.1->python-woc) (4.14.1)
Requirement already satisfied: exceptiongroup>=1.0.2 in /usr/local/lib/python3.9/site-packages (from anyio->httpx<0.29.0,>=0.28.1->python-woc) (1.3.0)

In [3]:
from woc.remote import WocMapsRemote
from tqdm import tqdm
import pandas as pd
# creates the client
woc = WocMapsRemote( base_url="https://worldofcode.org/api/")
# if you got an API key
# woc = WocMapsRemote( base_url="https://worldofcode.org/api/", api_key="woc-XXXXXX-YYYYYY" )

# Now for each of the ten projects you were assigned get commits, e.g.
projects = ['easystats/parameters',
    'ds4dm/Tulip.jl',
    'mtiller/ModelicaBook',
    'jdtuck/fdasrvf_R',
    'xbarin02/collatz',
    'Quantum-TII/qibo',
    'jklimke/libcitygml',
    'mskcc/vcf2maf',
    'sibrun/GH',
    'lyc102/ifem']
list_df_commits = []
for prj in projects:
  # Convert GitHub repository names to WoC V2412 project names
  prj = prj.lower().replace('/','_',2)
  commits = woc.get_values('p2c', prj)
  df = pd.DataFrame(commits, columns=["sha1"])
  df['project'] = prj
  list_df_commits.append(df)
df = pd.concat(list_df_commits)
#perhaps save the list (if no errors) so you do not need to retrieve them again
df.to_csv('df_commits.csv')
df.head(1)

                                       sha1               project
0  0000296a2d6ee34cf9e717583df06a38e7842062  easystats_parameters

In [4]:
# If the number of commits its not very large, you can try to get them all at the same time,
# The max batch size is 10
import time
# let us first split df['sha1'] in chunks
chunks = [df['sha1'][x:x+10] for x in range(0, len(df), 10)]
commit_data = []

for chunk in tqdm(chunks): # iterate over the commits
  # res, err = woc.show_content_many('commit',chunk.to_list())

  # commit.tch returns the same data but faster
  res, err = woc.get_values_many('commit.tch',chunk.to_list())
  res = {k: v[0] for k, v in res.items()}  # this conversion is necessary because of the internal implementation

  # to walk around the rate limit
  time.sleep(1)

  if err: # check for errors
    print('Got Errors', err)

  for commit_sha, commit in res.items():
    # flatten commit objects
    commit_data.append({
          'commit': commit_sha,
          'tree': commit[0],
          'parent': list(commit[1]),
          'author': commit[2][0],
          'author_time': int(commit[2][1]),
          'author_tz': commit[2][2],
          'committer': commit[3][0],
          'committer_time': int(commit[3][1]),
          'committer_tz': commit[3][2],
          'message': commit[4],
    })

df_commit_data = pd.DataFrame(commit_data)
df_commit_data = df_commit_data.merge(df, left_on='commit', right_on='sha1')
df_commit_data.to_csv('df_commit_data.csv', index=False)
df_commit_data.head(2)

  8%|████████████▊                                                                                                                                            | 267/3180 [04:32<49:33,  1.02s/it]

Got Errors {'4d050442e2c33da06a5ee4894fb01227c465a4b6': 'Key 4d050442e2c33da06a5ee4894fb01227c465a4b6 not found in /da5_fast/All.sha1c/commit_77.tch'}

 29%|████████████████████████████████████████████▎                                                                                                            | 922/3180 [15:54<39:20,  1.05s/it]

Got Errors {'4764a83171f6dd6363af12400381084140e1a168': 'Key 4764a83171f6dd6363af12400381084140e1a168 not found in /da5_fast/All.sha1c/commit_71.tch'}

 29%|████████████████████████████████████████████▋                                                                                                            | 930/3180 [16:03<39:07,  1.04s/it]

Got Errors {'60a366e96039dc446f5c1f4336f621e1691a5e31': 'Key 60a366e96039dc446f5c1f4336f621e1691a5e31 not found in /da5_fast/All.sha1c/commit_96.tch'}

 30%|█████████████████████████████████████████████▋                                                                                                           | 949/3180 [16:23<38:43,  1.04s/it]

Got Errors {'9009dfbe9936e231f962c842e6acb410b25d8674': 'Key 9009dfbe9936e231f962c842e6acb410b25d8674 not found in /da5_fast/All.sha1c/commit_16.tch'}

 31%|███████████████████████████████████████████████▌                                                                                                         | 988/3180 [17:03<37:59,  1.04s/it]

Got Errors {'0223292749b26923d8d695733cb1779330169c05': 'Key 0223292749b26923d8d695733cb1779330169c05 not found in /da5_fast/All.sha1c/commit_2.tch'}

 33%|██████████████████████████████████████████████████▌                                                                                                     | 1059/3180 [18:17<36:33,  1.03s/it]

Got Errors {'4b70ac4f9f380fefb37f407911a7e9fbba2e50c9': 'Key 4b70ac4f9f380fefb37f407911a7e9fbba2e50c9 not found in /da5_fast/All.sha1c/commit_75.tch'}

 34%|██████████████████████████████████████████████████▉                                                                                                     | 1066/3180 [18:24<36:24,  1.03s/it]

Got Errors {'503f1c89baeb69305978e3633663e0a4dc62b08e': 'Key 503f1c89baeb69305978e3633663e0a4dc62b08e not found in /da5_fast/All.sha1c/commit_80.tch'}

 34%|███████████████████████████████████████████████████▍                                                                                                    | 1077/3180 [18:35<36:07,  1.03s/it]

Got Errors {'5a6b2fc0d87163e0c282c13153d04f2f53c0cb5d': 'Key 5a6b2fc0d87163e0c282c13153d04f2f53c0cb5d not found in /da5_fast/All.sha1c/commit_90.tch'}

 35%|████████████████████████████████████████████████████▊                                                                                                   | 1105/3180 [19:04<35:50,  1.04s/it]

Got Errors {'78e8b616dd0169e9a4af0ded3fc9f3048e277ac0': 'Key 78e8b616dd0169e9a4af0ded3fc9f3048e277ac0 not found in /da5_fast/All.sha1c/commit_120.tch'}

 35%|█████████████████████████████████████████████████████▎                                                                                                  | 1116/3180 [19:15<35:31,  1.03s/it]

Got Errors {'82fb8b48ca6651726df47ae7966d241a34b67b85': 'Key 82fb8b48ca6651726df47ae7966d241a34b67b85 not found in /da5_fast/All.sha1c/commit_2.tch'}

 35%|█████████████████████████████████████████████████████▋                                                                                                  | 1123/3180 [19:23<35:22,  1.03s/it]

Got Errors {'8ad4bf9168a907a3657561880b1e221b7e4d5ef7': 'Key 8ad4bf9168a907a3657561880b1e221b7e4d5ef7 not found in /da5_fast/All.sha1c/commit_10.tch'}

 36%|██████████████████████████████████████████████████████▍                                                                                                 | 1140/3180 [19:40<35:09,  1.03s/it]

Got Errors {'9d208844063d0b2c1a196cc16b779f0a25c65ef6': 'Key 9d208844063d0b2c1a196cc16b779f0a25c65ef6 not found in /da5_fast/All.sha1c/commit_29.tch'}

 36%|███████████████████████████████████████████████████████▎                                                                                                | 1158/3180 [19:59<34:47,  1.03s/it]

Got Errors {'acd8aa6ed182d03176b0f45ef015f78b57a2ce8f': 'Key acd8aa6ed182d03176b0f45ef015f78b57a2ce8f not found in /da5_fast/All.sha1c/commit_44.tch'}

 37%|███████████████████████████████████████████████████████▌                                                                                                | 1163/3180 [20:04<34:44,  1.03s/it]

Got Errors {'b12497d41447d30d7e096a9e9a2514adc8a35b1f': 'Key b12497d41447d30d7e096a9e9a2514adc8a35b1f not found in /da5_fast/All.sha1c/commit_49.tch'}

 37%|████████████████████████████████████████████████████████▏                                                                                               | 1175/3180 [20:16<34:32,  1.03s/it]

Got Errors {'bbf5a9e52491fe22d0464dff75c4ccc2f3977461': 'Key bbf5a9e52491fe22d0464dff75c4ccc2f3977461 not found in /da5_fast/All.sha1c/commit_59.tch'}

 37%|████████████████████████████████████████████████████████▋                                                                                               | 1185/3180 [20:27<34:16,  1.03s/it]

Got Errors {'c5196c29b0e650cb6934296242f14720da2e954a': 'Key c5196c29b0e650cb6934296242f14720da2e954a not found in /da5_fast/All.sha1c/commit_69.tch'}

 38%|██████████████████████████████████████████████████████████▎                                                                                             | 1219/3180 [21:02<33:47,  1.03s/it]

Got Errors {'e71084f91cf43fda220dca4bc11b4fa995adf6b4': 'Key e71084f91cf43fda220dca4bc11b4fa995adf6b4 not found in /da5_fast/All.sha1c/commit_103.tch'}

 39%|██████████████████████████████████████████████████████████▉                                                                                             | 1233/3180 [21:16<33:28,  1.03s/it]

Got Errors {'f4fd62a46b42a4f80892e6d353fb125c2a852637': 'Key f4fd62a46b42a4f80892e6d353fb125c2a852637 not found in /da5_fast/All.sha1c/commit_116.tch'}

 39%|███████████████████████████████████████████████████████████▏                                                                                            | 1237/3180 [21:21<33:27,  1.03s/it]

Got Errors {'fa0e05208724a35facded8aa0217a8cbece48e94': 'Key fa0e05208724a35facded8aa0217a8cbece48e94 not found in /da5_fast/All.sha1c/commit_122.tch'}

 39%|███████████████████████████████████████████████████████████▎                                                                                            | 1241/3180 [21:25<33:21,  1.03s/it]

Got Errors {'fd2723e80955ef68114e2a788038ac0e5b3ca043': 'Key fd2723e80955ef68114e2a788038ac0e5b3ca043 not found in /da5_fast/All.sha1c/commit_125.tch'}

 39%|███████████████████████████████████████████████████████████▎                                                                                            | 1242/3180 [21:26<33:21,  1.03s/it]

Got Errors {'fe58cc87eb3b4799e55771ef61838092ea1223c5': 'Key fe58cc87eb3b4799e55771ef61838092ea1223c5 not found in /da5_fast/All.sha1c/commit_126.tch'}

 39%|███████████████████████████████████████████████████████████▉                                                                                            | 1253/3180 [21:37<33:38,  1.05s/it]

Got Errors {'1f3343a730546e83b117ed919416d0242686a7ab': 'Key 1f3343a730546e83b117ed919416d0242686a7ab not found in /da5_fast/All.sha1c/commit_31.tch', '1fc7e9a485571de952530cc3c88bebfd8c236433': 'Key 1fc7e9a485571de952530cc3c88bebfd8c236433 not found in /da5_fast/All.sha1c/commit_31.tch'}

 39%|████████████████████████████████████████████████████████████                                                                                            | 1256/3180 [21:40<33:38,  1.05s/it]

Got Errors {'28ef80f2fbd0521457298061ff5759be9fb2d3c7': 'Key 28ef80f2fbd0521457298061ff5759be9fb2d3c7 not found in /da5_fast/All.sha1c/commit_40.tch'}

 40%|████████████████████████████████████████████████████████████▏                                                                                           | 1259/3180 [21:43<33:29,  1.05s/it]

Got Errors {'322fd0de7ef35ca26848691c025efdae6f0e4f36': 'Key 322fd0de7ef35ca26848691c025efdae6f0e4f36 not found in /da5_fast/All.sha1c/commit_50.tch'}

 40%|████████████████████████████████████████████████████████████▎                                                                                           | 1261/3180 [21:46<33:28,  1.05s/it]

Got Errors {'371e1060b7ff3c0454d7453cd5caf56a956df4be': 'Key 371e1060b7ff3c0454d7453cd5caf56a956df4be not found in /da5_fast/All.sha1c/commit_55.tch'}

 40%|████████████████████████████████████████████████████████████▎                                                                                           | 1262/3180 [21:47<33:25,  1.05s/it]

Got Errors {'3792f632e71787a20a29e34418ee19adc42ab7ac': 'Key 3792f632e71787a20a29e34418ee19adc42ab7ac not found in /da5_fast/All.sha1c/commit_55.tch'}

 40%|████████████████████████████████████████████████████████████▌                                                                                           | 1267/3180 [21:52<34:02,  1.07s/it]

Got Errors {'492f70fc60084d4afcb43e47b8fbefc6495617be': 'Key 492f70fc60084d4afcb43e47b8fbefc6495617be not found in /da5_fast/All.sha1c/commit_73.tch'}

 40%|████████████████████████████████████████████████████████████▉                                                                                           | 1275/3180 [22:00<33:10,  1.04s/it]

Got Errors {'61d8cd680b7a0680650e1a1095fc0bfec82ab42f': 'Key 61d8cd680b7a0680650e1a1095fc0bfec82ab42f not found in /da5_fast/All.sha1c/commit_97.tch'}

 40%|█████████████████████████████████████████████████████████████▎                                                                                          | 1283/3180 [22:09<32:52,  1.04s/it]

Got Errors {'7605e1491503bfe5a9e4d477fce45dabbfc091f9': 'Key 7605e1491503bfe5a9e4d477fce45dabbfc091f9 not found in /da5_fast/All.sha1c/commit_118.tch'}

 41%|█████████████████████████████████████████████████████████████▊                                                                                          | 1292/3180 [22:18<32:52,  1.04s/it]

Got Errors {'8d418e571ecc201d521f6f68e9437ed110f0708f': 'Key 8d418e571ecc201d521f6f68e9437ed110f0708f not found in /da5_fast/All.sha1c/commit_13.tch'}

 41%|██████████████████████████████████████████████████████████████▍                                                                                         | 1306/3180 [22:33<32:42,  1.05s/it]

Got Errors {'b68c23b5ac4e84fa913d931d07ab1aaca756e2f2': 'Key b68c23b5ac4e84fa913d931d07ab1aaca756e2f2 not found in /da5_fast/All.sha1c/commit_54.tch'}

 41%|██████████████████████████████████████████████████████████████▋                                                                                         | 1312/3180 [22:39<32:34,  1.05s/it]

Got Errors {'c749dd41877353eb19556b352f9a1969ca294d69': 'Key c749dd41877353eb19556b352f9a1969ca294d69 not found in /da5_fast/All.sha1c/commit_71.tch'}

 41%|██████████████████████████████████████████████████████████████▉                                                                                         | 1318/3180 [22:45<32:28,  1.05s/it]

Got Errors {'d5b55ba030993c67c9b0af39c32215aa4c248d64': 'Key d5b55ba030993c67c9b0af39c32215aa4c248d64 not found in /da5_fast/All.sha1c/commit_85.tch'}

 42%|███████████████████████████████████████████████████████████████▏                                                                                        | 1323/3180 [22:51<32:20,  1.05s/it]

Got Errors {'e17e2d12291a929eac7b34c8c114193cc68c3d9f': 'Key e17e2d12291a929eac7b34c8c114193cc68c3d9f not found in /da5_fast/All.sha1c/commit_97.tch'}

 42%|███████████████████████████████████████████████████████████████▎                                                                                        | 1325/3180 [22:53<32:19,  1.05s/it]

Got Errors {'e7b98ae316238723caca70e288fd74db5754cae5': 'Key e7b98ae316238723caca70e288fd74db5754cae5 not found in /da5_fast/All.sha1c/commit_103.tch'}

 42%|███████████████████████████████████████████████████████████████▋                                                                                        | 1332/3180 [23:00<32:04,  1.04s/it]

Got Errors {'f8ae9af475e4dfe2cd6f62a25b58af978fc1e259': 'Key f8ae9af475e4dfe2cd6f62a25b58af978fc1e259 not found in /da5_fast/All.sha1c/commit_120.tch', 'f92a11e194101d15b53c30e9661bf12aeacadc33': 'Key f92a11e194101d15b53c30e9661bf12aeacadc33 not found in /da5_fast/All.sha1c/commit_121.tch'}

 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏           | 2933/3180 [50:50<04:18,  1.05s/it]

Got Errors {'0a403bbe3319712ab01a65a1f1eadc114e65628d': 'Key 0a403bbe3319712ab01a65a1f1eadc114e65628d not found in /da5_fast/All.sha1c/commit_10.tch'}

 93%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊           | 2946/3180 [51:04<04:04,  1.05s/it]

Got Errors {'43835d360dbb863045c2bf558663a06dbdbb5eaf': 'Key 43835d360dbb863045c2bf558663a06dbdbb5eaf not found in /da5_fast/All.sha1c/commit_67.tch'}

 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████           | 2952/3180 [51:10<03:58,  1.04s/it]

Got Errors {'5c278240a7eb1f3886d74c5e5f4ecf69834ef25a': 'Key 5c278240a7eb1f3886d74c5e5f4ecf69834ef25a not found in /da5_fast/All.sha1c/commit_92.tch'}

 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏          | 2955/3180 [51:13<03:54,  1.04s/it]

Got Errors {'65e06ef9dade4dba265eebf5c7b1b3430f2efb6c': 'Key 65e06ef9dade4dba265eebf5c7b1b3430f2efb6c not found in /da5_fast/All.sha1c/commit_101.tch'}

 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍          | 2960/3180 [51:19<03:49,  1.04s/it]

Got Errors {'79a2892f108effd368c71ef31fa5b2e832f03f0e': 'Key 79a2892f108effd368c71ef31fa5b2e832f03f0e not found in /da5_fast/All.sha1c/commit_121.tch'}

 93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋          | 2965/3180 [51:24<03:44,  1.04s/it]

Got Errors {'9327a6cc19852e4de6409fc21526d5fd215c3eda': 'Key 9327a6cc19852e4de6409fc21526d5fd215c3eda not found in /da5_fast/All.sha1c/commit_19.tch'}

 94%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎         | 2977/3180 [51:36<03:31,  1.04s/it]

Got Errors {'c899646e406d33fae408416178c59884daef2302': 'Key c899646e406d33fae408416178c59884daef2302 not found in /da5_fast/All.sha1c/commit_72.tch'}

 94%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍         | 2981/3180 [51:40<03:27,  1.04s/it]

Got Errors {'d5a73fac8a6a9568f5a25f2358f2e61c82159177': 'Key d5a73fac8a6a9568f5a25f2358f2e61c82159177 not found in /da5_fast/All.sha1c/commit_85.tch'}

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3180/3180 [55:09<00:00,  1.04s/it]

,commit,tree,parent,author,author_time,author_tz,committer,committer_time,committer_tz,message,sha1,project
0,0000296a2d6ee34cf9e717583df06a38e7842062,ffe4f603197ede26c59e16c6e791784e5da716e0,[2e3fdcdc4193569ac16e27e88bb3462870db3b97],Daniel <mail@danielluedecke.de>,1684657123,+0200,Daniel <mail@danielluedecke.de>,1684657123,+0200,Bug: `parameters` no longer respects the `vcov...,0000296a2d6ee34cf9e717583df06a38e7842062,easystats_parameters
1,000349ee3bbfe4b011a29a30f6d47a7a9486f5f6,d8e25e3c16d7ce476b7511e63dd79319529cd7b7,[dd955429c028f21baee6aa40160be1ae6653b4b6],GitHub Actions <actions@github.com>,1616069558,+0000,GitHub Actions <actions@github.com>,1616069558,+0000,Built site for parameters: 0.12.0.1@14c1600\n,000349ee3bbfe4b011a29a30f6d47a7a9486f5f6,easystats_parameters

In [5]:
# what does the first record looks like?
# commit  parents
v = commit_data[0]
# commit tree, [parent{s}], [author, unixtime, tz ], [ committer, unixtime, tz ], Commit_message ]
print(v)

{'commit': '0000296a2d6ee34cf9e717583df06a38e7842062', 'tree': 'ffe4f603197ede26c59e16c6e791784e5da716e0', 'parent': ['2e3fdcdc4193569ac16e27e88bb3462870db3b97'], 'author': 'Daniel <mail@danielluedecke.de>', 'author_time': 1684657123, 'author_tz': '+0200', 'committer': 'Daniel <mail@danielluedecke.de>', 'committer_time': 1684657123, 'committer_tz': '+0200', 'message': 'Bug: `parameters` no longer respects the `vcov` argument\nFixes #881\n'}

In [6]:
# Now that the data is retrieved, save it and commit to your GH fork
# First, we need to flatten info in order to export as csv
# our dataframe will have columns project,'commit, author, time, message'
dfinf = pd.DataFrame(columns=['project', 'commit', 'author', 'time', 'message'])
for k in commit_data:
  row = pd.Series({'project':prj, 'commit': k['commit'], 'author': k['author'], 'time': k['author_time'], 'message':k['message']})
  dfinf = pd.concat([dfinf, row.to_frame().T ], ignore_index=True)

In [7]:
# check if it has the right content
dfinf.head(1)

,project,commit,author,time,message
0,lyc102_ifem,0000296a2d6ee34cf9e717583df06a38e7842062,Daniel <mail@danielluedecke.de>,1684657123,Bug: `parameters` no longer respects the `vcov...

In [8]:
#mode a means append, so you have all your projects in the same file
yournetid='your_net_id_here'
dfinf.to_csv(yournetid+'_project_summary.csv', index=False,sep=';', mode='a', header=False)

# Make sure you check in to your fork not just the notebook but also the csv files!!!

# Don't forget to add requested data from github and this notebook
### For each of the 10 projects go to their github repo and get the number of stars, number of forks, and the last commit date
### Report (in your notebook) the number of commits, the number of authors, and max and min time for each project based on WoC commits and also add the info you obtained from github

Repo Name: easystats_parameters

Stars: 499

Forks: 46

Last Commit Date: 10/5/2026



Repo Name: ds4dm_tulip.jl

Stars: 163

Forks: 24

Last Commit Date: April 19, 2026



Repo Name: mtiller_modelicabook

Stars: 117

Forks: 75

Last Commit Date: September 6, 2026



Repo Name: jdtuck_fdasrvf_r

Stars: 15

Forks: 18

Last Commit Date: September 30, 2026



Repo Name: xbarin02_collatz

Stars: 84

Forks: 7

Last Commit Date: October 5, 2026



Repo Name: quantum-tii_qibo

Stars: 366

Forks: 104

Last Commit Date: October 7, 2026



Repo Name: jklimke_libcitygml

Stars: 111

Forks: 59

Last Commit Date: November 25, 2025



Repo Name: mskcc_vcf2maf

Stars: 421

Forks: 219 

Last Commit Date: May 25, 2026



Repo Name: sibrun_gh

Stars: 2

Forks: 3

Last Commit Date: March 11, 2026



Repo Name: lyc102_ifem

Stars: 297

Forks: 99

Last Commit Date: August 19, 2026

In [13]:
import pandas as pd

for project in df_commit_data["project"].unique():
    project_df = df_commit_data[df_commit_data["project"] == project]

    num_commits = project_df["commit"].nunique()
    num_authors = project_df["author"].nunique()

    min_time = project_df["author_time"].min()
    max_time = project_df["author_time"].max()

    print("Project:", project)
    print("Number of commits:", num_commits)
    print("Number of authors:", num_authors)
    print("Min time:", min_time)
    print("Max time:", max_time)
    print()

Project: easystats_parameters
Number of commits: 8925
Number of authors: 76
Min time: 1549684900
Max time: 1776169631

Project: ds4dm_tulip.jl
Number of commits: 926
Number of authors: 29
Min time: 1524835025
Max time: 1759338898

Project: mtiller_modelicabook
Number of commits: 2558
Number of authors: 69
Min time: 1354808010
Max time: 1742473600

Project: jdtuck_fdasrvf_r
Number of commits: 891
Number of authors: 25
Min time: 1347235093
Max time: 1760872097

Project: xbarin02_collatz
Number of commits: 1462
Number of authors: 4
Min time: 1564771496
Max time: 1762345592

Project: quantum-tii_qibo
Number of commits: 14496
Number of authors: 137
Min time: 1582014071
Max time: 1762323672

Project: jklimke_libcitygml
Number of commits: 598
Number of authors: 58
Min time: 1349083662
Max time: 1760908890

Project: mskcc_vcf2maf
Number of commits: 498
Number of authors: 42
Min time: 1385144375
Max time: 1754097415

Project: sibrun_gh
Number of commits: 1032
Number of authors: 11
Min time: 1511974982
Max time: 1759782875

Project: lyc102_ifem
Number of commits: 359
Number of authors: 14
Min time: 1559804633
Max time: 1760729466